language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t bandit79/docker-fullstack-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true bandit79/react-test-app npm test

after_success:
  - docker build -t bandit79/docker-frontend ./frontend
  - docker build -t bandit79/docker-backend ./backend
  - docker build -t bandit79/docker-nginx ./nginx

  - docker login -u bandit79 -p Zrmfkqldh81!

  - docker push bandit79/docker-frontend
  - docker push bandit79/docker-backend
  - docker push bandit79/docker-nginx

