language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t bandit79/react-test-app -f /home/omnione/z_docker_test2/docker-full-stack-app/frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true bandit79/react-test-app npm run test

after_sucess:
  - docker build -t bandit79/docker-frontend ./frontend
  - docker build -t bandit79/docker-backend ./backend
  - docker build -t bandit79/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push bandit79/docker-frontend
  - docker push bandit79/docker-backend
  - docker push bandit79/docker-nginx

  
